name: news
recipe: drupal10
config:
  webroot: web
  via: nginx
  php: 8.2
proxy:
  mailhog:
   - mailhog.lndo.site
services:
  mailhog:
    type: mailhog
    hogfrom:
     - appserver
    portforward: true
